# Dockerfile for providing a test environment for Windows developers

FROM python:3.6
ENV PYTHONUNBUFFERED 1

# Requirements have to be pulled and installed here, otherwise caching won't work
COPY ./requirements /requirements
RUN pip install -r /requirements/test.txt

# Install cdi-linking
COPY ./cdi-linking /lib/cdi-linking
# The cdi-linking requires the readme.rst file to be one directory above itself
COPY ./readme.rst /lib/readme.rst
RUN pip install -e /lib/cdi-linking/

# Install linking_ext
COPY ./linking_ext /lib/linking_ext
RUN pip install -e /lib/linking_ext/

WORKDIR /lib

# Default container action - run Pytest tests
CMD ["pytest", "--cov=cdilinker"]
